# #####################################################################
# Automatically generated by qmake (2.01a) sex ago 21 00:31:25 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += . \
    qtc-gdbmacros
INCLUDEPATH += .

# Input
HEADERS += phononp.hpp \
    collectionTree.h \
    playlistTable.h \
    ContextInterface.h \
    scanCollection.h \
    scanAlgorithm.h \
    pluginManager.h
SOURCES += main.cpp \
    phononp.cpp \
    gdbmacros.cpp \
    collectionTree.cpp \
    playlistTable.cpp \
    scanCollection.cpp \
    scanAlgorithm.cpp \
    pluginManager.cpp
QT += phonon
FORMS += configureWidget.ui \
    pluginManager.ui
RESOURCES += phononp.qrc
